import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ModalX from '@/modals/modal';
import { ModalProvider } from '@/context/modal-context';
import { ThemeProvider } from '@/components/theme-provider';
import { Footer } from '@/components/footer';
import { Providers } from './provider';
import { AuthProvider } from '@/context/auth-context';
import { ToastContainer } from 'react-toastify';
import RoleNavigatorWithProtection from './role-navigator';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <AuthProvider>
              <ToastContainer />
              <ModalProvider>
                <ModalX />
                <RoleNavigatorWithProtection>
                  {children}
                </RoleNavigatorWithProtection>
                <Footer />
              </ModalProvider>
            </AuthProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
